### ISSUE TITLE
Add a better exception handler for missing template config files

### ISSUE THREAD

**Issue by kvorak** [Project-0/lpm#2]
Currently, if there is _no_ `.lpm.config` file in the search path, it errors out saying:

```
Traceback (most recent call last):
  File "/home/<usr>/<project_path>/lpm/lpm.git/lpm/__main__.py", line 84, in <module>
    main()
  File "/home/<usr>/<project_path>/lpm/lpm.git/lpm/__main__.py", line 52, in main
    templates = yaml.load(open(os.path.expanduser(full_path), 'r+'))
IOError: [Errno 2] No such file or directory: '/usr/local/lpm/templates/index.yaml'
```
*Solution*
If it can't find an actual config file anywhere, it should resolve one from the current `config_file` (an instance of `LPMConfigParser`).  This probably means adding a member to `LPMConfigParser` that exports a formatted YAML object.

**Comment by kvorak** [comment]
We should create a method to create standard template config files.
